import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,mkdir,writeFile,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import path from 'node:path';
import {validateBatch,canonicalUrl,planBatch,applyBatch,loadState} from './news-batch.mjs';
const now='2026-09-20T12:00:00Z';
function fixture(){const batch={runId:'2026-09-20',asOf:now,items:Array.from({length:10},(_,i)=>({article:{id:`test-${i}`,category:'industrial-robots',title:`ข่าวภาษาไทยหมายเลข ${i}`,summary:'สรุปข่าวที่ตรวจสอบจากต้นฉบับ',source:`Source ${i%3}`,date:'2026-09-20',url:`https://source${i%3}.example/news/${i}`,image:''},detail:{sections:Array.from({length:4},()=>({heading:'รายละเอียด',paragraphs:['ข้อมูลจากบทความต้นฉบับสำหรับทดสอบการตรวจสอบรายละเอียดข่าว '.repeat(4)]}))},media:{images:[],videos:[]},editorial:{storyKey:`company-${i}-product-launch`,originalTitle:`Company ${i} reveals unique product ${i}`,publishedAt:now,reason:'ผลิตภัณฑ์ใหม่มีการสาธิตใช้งานจริง',score:17,sourceUrls:[`https://source${i%3}.example/news/${i}`],duplicateReviewed:true,mediaReviewed:true,discoveredImages:[],discoveredVideos:[],excludedMedia:[]}}))};for(const item of batch.items)item.english={title:'An English title for '+item.article.id,summary:'An original English summary of this robotics development.',sections:Array.from({length:3},()=>({heading:'Verified details',paragraphs:['This English section explains the verified development and its practical implications, distinguishing current results from future plans.']})),images:[],videos:[]};return batch}
const state={articles:[],details:{},media:{},english:{},history:{version:1,stories:[],runs:[]}};
test('accepts ten fresh diverse fully reviewed stories',()=>assert.equal(validateBatch(fixture(),state,new Date(now)).length,10));
test('rejects a short batch instead of padding or publishing eight',()=>{const b=fixture();b.items.pop();assert.throws(()=>validateBatch(b,state,new Date(now)),/10/)});
test('rejects cross-source syndication by story key',()=>{const b=fixture();const existing={...state,history:{...state.history,stories:[{id:'older',storyKey:b.items[0].editorial.storyKey,urls:['https://another.example/announcement']}]}};assert.throws(()=>validateBatch(b,existing,new Date(now)),/duplicate/i)});
test('canonical URL removes tracking, fragments, protocol and www differences',()=>assert.equal(canonicalUrl('http://www.example.com/post/?utm_source=x&fbclid=y#section'),canonicalUrl('https://example.com/post')));
test('rejects URL aliases already published',()=>{const b=fixture();b.items[0].article.url='https://www.example.com/news?utm_source=feed';const existing={...state,articles:[{id:'old',title:'ต่างชื่อ',url:'http://example.com/news'}]};assert.throws(()=>validateBatch(b,existing,new Date(now)),/duplicate/i)});
test('rejects repeated IDs, missing media, unsafe embeds and stale stories',()=>{let b=fixture();b.items[1].article.id=b.items[0].article.id;assert.throws(()=>validateBatch(b,state,new Date(now)),/duplicate/i);b=fixture();b.items[0].editorial.discoveredVideos=['https://youtu.be/abcdefghijk'];assert.throws(()=>validateBatch(b,state,new Date(now)),/media/i);b=fixture();b.items[0].article.id='../escape';assert.throws(()=>validateBatch(b,state,new Date(now)),/id/i);b=fixture();b.items[0].editorial.publishedAt='2020-01-01T00:00:00Z';assert.throws(()=>validateBatch(b,state,new Date(now)),/fresh/i)});
test('rejects future timestamps',()=>{const b=fixture();b.items[0].editorial.publishedAt='2026-09-21T00:00:00Z';assert.throws(()=>validateBatch(b,state,new Date(now)),/future/i)});

test('identical retry is a no-op after expiry; changed same-run batch fails',()=>{const b=fixture(),first=planBatch(b,state,new Date(now));assert.equal(first.next.articles.length,10);assert.equal(planBatch(b,first.next,new Date('2026-10-01')).alreadyApplied,true);b.items[0].article.title+='เปลี่ยน';assert.throws(()=>planBatch(b,first.next,new Date(now)),/different content/)});
test('disk import preserves existing data and retry never duplicates it',async()=>{const root=await mkdtemp(path.join(tmpdir(),'robotnews-test-'));try{await mkdir(path.join(root,'content'));const original={...state,articles:[{id:'legacy',title:'ข่าวเดิม',url:'https://old.example/story'}],details:{legacy:{sections:[]}},media:{legacy:{images:[],videos:[]}}};for(const [file,value] of Object.entries({'articles.json':original.articles,'details.json':original.details,'media.json':original.media,'news-history.json':original.history,'english.json':original.english}))await writeFile(path.join(root,'content',file),JSON.stringify(value));await applyBatch(fixture(),root,new Date(now));assert.equal((await applyBatch(fixture(),root,new Date('2026-10-01'))).alreadyApplied,true);const result=await loadState(root);assert.equal(result.articles.length,11);assert.deepEqual(result.details.legacy,original.details.legacy);assert.equal(result.history.runs.length,1)}finally{await rm(root,{recursive:true,force:true})}});

test('distinct events may share supporting citations but not identity aliases',()=>{const b=fixture();b.items.forEach(i=>i.editorial.sourceUrls.push('https://research.example/shared-paper'));assert.equal(validateBatch(b,state,new Date(now)).length,10);b.items[1].editorial.identityUrls=[b.items[0].article.url];assert.throws(()=>validateBatch(b,state,new Date(now)),/Duplicate source/)});

test('daily batches require complete English translations before import',()=>{const b=fixture();delete b.items[0].english;assert.throws(()=>validateBatch(b,state,new Date(now)),/English translation/)});
